### ISSUE TITLE
Inclusione italia-icon-font.css errata in documentazione readme.md

### ISSUE THREAD

**Issue by tizianolattisi** [italia/design-angular-kit#100]
## Comportamento atteso
Provando a seguire le indicazioni nel file readme.md ho notato la presenza di un riferimento al file obsoleto italia-icon-font.css che impedisce la build.

## Comportamento attuale
Interando il riferimento come proposto da docuentazione si ottiene un Module not found: Error: Can't resolve '[...]italia-icon-font.css'

## Possibili soluzioni
Aggiornare la documentazione rimuovendo il riferimento a italia-icon-font.css nel file readme.md.

**Comment by francescozaia** [comment]
Hai ragione @tizianolattisi, purtroppo è un po' che il kit Angular non è mantenuto e purtroppo ormai si basa su una versione di Bootstrap Italia non aggiornata.

Chiunque abbia voglia di metterci mano è il benvenuto!

**Comment by giovanisp** [comment]
salve, esiste una nuova versione del kit oppure questa è quella consigliata?

**Comment by astagi** [comment]
@giovanisp stiamo lavorando a una nuova versione del kit e attualmente abbiamo spostato lo sviluppo su main, il maintainer di riferimento è @cri99. Ogni contributo è il benvenuto 😃
