### ISSUE TITLE
Migliorare la compatibilità con Angular 9 e form <it-input>

### ISSUE THREAD

**Issue by cicarulez** [italia/design-angular-kit#101]
## Comportamento atteso
Comportamento normale della form del componente <it-input> con approccio TemplateDriven o ReactiveForm

## Comportamento attuale
Con angular9, entrambi gli approcci non funzionano, il valore della form non viene passato al componente typescript

**Comment by astagi** [comment]
@cicarulez è con grande piacere che ti annuncio che i lavori su Angular Kit sono ufficialmente ripartiti grazie al lavoro di @cri99 che seguirà i prossimi sviluppi 🙌

Issue di riferimento: https://github.com/italia/design-angular-kit/issues/126
Discussione: https://github.com/italia/design-angular-kit/discussions/127
