### ISSUE TITLE
Inserire file CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by nsanitate** [italia/design-angular-kit#13]
## Comportamento atteso

Nel repository dovrebbe essere presente il file CODE_OF_CONDUCT.md contenente le regole di comportamento della comunità.

## Comportamento attuale

File non presente.

## Possibili soluzioni

Prendere spunto dal rispettivo file nel repository di [bootstrap-italia](https://github.com/italia/bootstrap-italia/blob/master/CODE_OF_CONDUCT.md)

**Comment by sanyamdogra** [comment]
Claim

**Comment by astagi** [comment]
Aggiunto @nsanitate grazie!
