### ISSUE TITLE
Rimuovere codice interattivo e atomicizzare codice degli esempi

### ISSUE THREAD

**Issue by astagi** [italia/design-angular-kit#133]
## Comportamento atteso

Il codice interattivo dei componenti deve essere rimosso, inoltre gli esempi devono essere atomicizzati.

## Comportamento attuale

Il codice interattivo spesso è lungo e confusionario, serve per il rendering del componente comunque. I vari esempi dovrebbero essere atomicizzati.

**Comment by stepobiz** [comment]
Qunado parli di condice interattivo ti riferisci a file tpl che generano i file html dei componenti come questo: https://github.com/italia/design-angular-kit/blob/main/src/app/pagination/pagination-examples/pagination-examples.component.tpl ? 

Se si cosa intendi per "esempi atomicizzati"?

Grazie

**Comment by AntoninoBonanno** [comment]
Non so a cosa si riferiva @astagi ma avrei intenzione di effettuare un grosso refactoring e migliorie per la parte di documentazione. Dovrei iniziare a lavorarci verso la seconda settimana di settembre

**Comment by AntoninoBonanno** [comment]
Si per il momento puoi dare minor priorità a questo task. Credo che in generale questo task sia per migliorare la documentazione.. avevo iniziato io a fare qualcosina ma per il momento è in standby.

**Comment by AntoninoBonanno** [comment]
@astagi rinominerei questo task per il miglioramento generale della documentazione. Me ne occupo io
