### ISSUE TITLE
Add docs and tests for component Alert

### ISSUE THREAD

**Issue by astagi** [italia/design-angular-kit#136]
## Description

Add docs and tests for component `Alert` following the vanilla JS implementation present in [Bootstrap Italia documentation](https://italia.github.io/bootstrap-italia/docs/componenti/alert/).

## Checklist

- [ ] Verify and update, markup and classes of the resulting DOM template, compared to Bootstrap Italia 2
- [ ] Check the rendering of the component (CSS application including spacing, dimensions, typography, ...), compared to Bootstrap Italia and the new UI kit
- [ ] Check the behavior of the component (JavaScript, user interaction, states, keyboard interaction for accessibility, ...), compared to Bootstrap Italia 2
- [ ] Verify the accessibility of the component, including automatic tests and manual evaluations by a11y experts, if possible
- [ ] Evaluate the need to supplement documentation with more detailed information.
- [ ] Write tests for this component
- [ ] Write documentation for this component

**Comment by angelo24983** [comment]
vorrei provare a prendere in carico questa issue

**Comment by astagi** [comment]
@angelo24983 ho visto la reference sul tuo fork, se tutto pronto puoi inviare una Pull request verso questo repository?

**Comment by astagi** [comment]
@angelo24983 abbiamo inserito su `main` una grossa contribuzione di @AntoninoBonanno, il componente `Alert` risulta già implementato, volendo puoi ripartire da `main` e creare test e documentazione per questo componente. Un saluto e grazie!

**Comment by angelo24983** [comment]
@astagi ok a questo punto conviene che faccio fork direttamente della nuova versione del progetto e lavoro su test e documentazione.

**Comment by astagi** [comment]
Esatto @angelo24983 ! Grazie mille!!
