### ISSUE TITLE
Create component Chip

### ISSUE THREAD

**Issue by astagi** [italia/design-angular-kit#141]
## Description

Create component `Chip` following the vanilla JS implementation present in [Bootstrap Italia documentation](https://italia.github.io/bootstrap-italia/docs/componenti/chips/).

## Checklist

- [ ] Verify and update, markup and classes of the resulting DOM template, compared to Bootstrap Italia 2
- [ ] Check the rendering of the component (CSS application including spacing, dimensions, typography, ...), compared to Bootstrap Italia and the new UI kit
- [ ] Check the behavior of the component (JavaScript, user interaction, states, keyboard interaction for accessibility, ...), compared to Bootstrap Italia 2
- [ ] Verify the accessibility of the component, including automatic tests and manual evaluations by a11y experts, if possible
- [ ] Evaluate the need to supplement documentation with more detailed information.
- [ ] Write tests for this component
- [ ] Write documentation for this component

**Comment by alenap93** [comment]
prendo in carico

**Comment by astagi** [comment]
Assegno grazie @alenap93 poi lunedì controllo e mergio tutto!!
