### ISSUE TITLE
Create component Dimmer

### ISSUE THREAD

**Issue by astagi** [italia/design-angular-kit#142]
## Description

Create component `Dimmer` following the vanilla JS implementation present in [Bootstrap Italia documentation](https://italia.github.io/bootstrap-italia/docs/componenti/dimmer/).

## Checklist

- [ ] Verify and update, markup and classes of the resulting DOM template, compared to Bootstrap Italia 2
- [ ] Check the rendering of the component (CSS application including spacing, dimensions, typography, ...), compared to Bootstrap Italia and the new UI kit
- [ ] Check the behavior of the component (JavaScript, user interaction, states, keyboard interaction for accessibility, ...), compared to Bootstrap Italia 2
- [ ] Verify the accessibility of the component, including automatic tests and manual evaluations by a11y experts, if possible
- [ ] Evaluate the need to supplement documentation with more detailed information.
- [ ] Write tests for this component
- [ ] Write documentation for this component

**Comment by alenap93** [comment]
prendo in carico

**Comment by astagi** [comment]
perfetto grazie @alenap93 . Appena possibile guardiamo anche l'altra PR 🙌

**Comment by alenap93** [comment]
@astagi il componente è pronto ma purtroppo #166, non mi permette di portarlo a termine

**Comment by astagi** [comment]
Ottimo @alenap93 ! Purtroppo fino al 9 non posso mettere mano al codice, lascio la discussione a @AntoninoBonanno e @cri99

**Comment by cri99** [comment]
@astagi @alenap93 La discussione prosegue sull'issue #166.

> @astagi il componente è pronto ma purtroppo #166 non mi permette di portarlo a termine https://github.com/alenap93/design-angular-kit/tree/dimmer

Per quanto riguarda il componente button, la discussione prosegue sull'issue #166
