### ISSUE TITLE
Complete Header Component

### ISSUE THREAD

**Issue by astagi** [italia/design-angular-kit#161]
## Description

Complete and add docs and tests for component `Header` following the vanilla JS implementation present in [Bootstrap Italia documentation](https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/header/).

## Checklist

- [ ] Verify and update, markup and classes of the resulting DOM template, compared to Bootstrap Italia 2
- [ ] Check the rendering of the component (CSS application including spacing, dimensions, typography, ...), compared to Bootstrap Italia and the new UI kit
- [ ] Check the behavior of the component (JavaScript, user interaction, states, keyboard interaction for accessibility, ...), compared to Bootstrap Italia 2
- [ ] Verify the accessibility of the component, including automatic tests and manual evaluations by a11y experts, if possible
- [ ] Evaluate the need to supplement documentation with more detailed information.
- [ ] Write tests for this component
- [ ] Write documentation for this component

**Comment by stepobiz** [comment]
Disponibile allo sviluppo

**Comment by stepobiz** [comment]
In sviluppo sul seguente branch: https://github.com/stepobiz/design-angular-kit/tree/feature/header
Ho completato il grosso del lavoro, per farlo ho usato il componente header già preparato dal buon @AntoninoBonanno.

Ho aggiunto un componente menu, per gestire i vari menù presenti nell'header, l'ho fatto abbastanza generico in modo che può essere riusato altrove.

Ecco cosa rimane:
- Nome Ente ed informazioni statiche, come vanno gestite?
- Giro di test ed eventuali correzioni di segnalazioni.

Aspetto vostre

**Comment by AntoninoBonanno** [comment]
Ciao grazie per il contributo.

Per "Nome Ente ed informazioni statiche, come vanno gestite?" puoi impostare degli input o selettori in modo che lo sviluppatore può configurare questi parametri durante lo sviluppo dell'applicazione

**Comment by stepobiz** [comment]
Ok. nell'header che ho trovato sono stati gestiti alcuni contenuti con dei `<ng-content [selector]=....>` possiamo sentirci su slack per capire se li elimino oppure porto avanti questo tipo di implementazione?

**Comment by AntoninoBonanno** [comment]
Se è utile manterrei i selettori. 
Sii, ci possiamo sentire su slack.

**Comment by lucafulgenzi** [comment]
Ci sta lavorando qualcuno sull'header?

**Comment by lucafulgenzi** [comment]
@AntoninoBonanno @stepobiz  sta lavorando qualcuno su questo componente? Altrimenti posso portare avanti il io lavoro da fare.

**Comment by AntoninoBonanno** [comment]
Ciao @lucafulgenzi , grazie. Io al momento no

**Comment by astagi** [comment]
Grazie @lucafulgenzi se vuoi aprire una PR ben venga ti posso dare una mano!

**Comment by lucafulgenzi** [comment]
@astagi al momento non ho il tempo per continuare a sviluppare il componente, appena possibile sicuramente la faró.

**Comment by astagi** [comment]
> @astagi al momento non ho il tempo per continuare a sviluppare il componente, appena possibile sicuramente la faró.

Figurati @lucafulgenzi anzi grazie dell'interesse. Se riesco a cominciare qualcosa io ti aggiorno.

**Comment by lucafulgenzi** [comment]
Ho quasi fatto tutti gli esempi che ci sono su bootstrap italia, manca solo qualcosa a livello grafico, se qualcuno riuscisse a pullare la mia fork , provare il componente e dirmi se c´é qualcosa che non funziona.

_Premessa_

Il componente header navbar non viene visualizzato correttamente
Gli z-index sono un pó sballati

**Comment by lucafulgenzi** [comment]
Ho fatto tutti gli esempi che erano presenti su bootstrap italia, per quello che mi riguarda il componente header sembra funzionare a dovere.

Chiedo solo a chi se ne occupa di fixare il css generale, poiché gli z-index degli header sono un pó sballati. Mi riferisco soprattuto alla sidebar che esce dalla navbar mobile. Ovviamente in un contesto di produzione non darebbe problemi, poiché sarebbe in linea con il css generale, ma nel caso di `italia.github.io` l'header generale sembra avere uno z-index troppo grande.
