### ISSUE TITLE
Riportare il componente button a direttiva

### ISSUE THREAD

**Issue by alenap93** [italia/design-angular-kit#166]
## Comportamento atteso
I componenti non devono confliggere con i css di bootrap italia, usare it-button deve avere lo stesso comportamento di un button classico.

## Comportamento attuale
Attualmente ipotizzando dobbiamo usare due button, con gli it-button come componente otteniamo una struttura:
```
<it-button>
 <button></button>
</it-button>
<it-button>
 <button></button>
</it-button>
```
questa struttura confligge con l'uso canonico dei css di bootstrap italia, in quanto (siccome sto sviluppando il componente Dimmer, mi sono accorto di ciò) ci ritroviamo scss come il seguente:
```
.dimmer-buttons {
    background-color: transparent !important;
    margin-top: $v-gap * 4;
    display: flex;
    justify-content: space-between;
    flex-wrap: wrap;
    button {
      width: 100%;
      &:last-child {
        margin-top: $v-gap * 2;
      }
    }
    &.single-button {
      button {
        margin-top: 0;
      }
    }
  }
```
che, incidendo direttamente sul button last child, nell'esempio dei due button precedenti verrebbe applicata ad entrambi, in quanto entrambi sono last-child, ma cosi non è.

## Possibili soluzioni

Possibile soluzione è tornare a it-button come direttiva, come era nella 1.0.0-1 (https://github.com/italia/design-angular-kit/blob/v1.0.0-1/projects/design-angular-kit/src/lib/button/button.directive.ts).

**Comment by cri99** [comment]
Grazie per la segnalazione @alenap93.

@AntoninoBonanno potresti indicarci se vedi criticità nel ritornare all'implementazione del bottone come direttiva invece che come componente?

**Comment by AntoninoBonanno** [comment]
Non vedo criticità, 
ovviamente essendo cambiate le interfacce/enumerativi e con l'introduzione dei nuovi componenti la vecchia direttiva deve essere adattata. 

Provvedo di effettuare questa modifica così da sbloccare @alenap93
