### ISSUE TITLE
Click su pulsante menu e switch tab con API non funziona

### ISSUE THREAD

**Issue by alenap93** [italia/design-angular-kit#167]
## Comportamento atteso
Al click sul pulsante Menu, che appare quando si ha un device con larghezza inferiore ai 768px, il menu dovrebbe mostrarsi o nascondersi.

## Comportamento attuale
Sull'ultima versione, ancora solo in preview (https://design-angular-eejl2kfcd-dip-trasformazione-digitale.vercel.app/) , accedendo con schermo sotto i 768px, il click sul pulsante Menu non produce alcun risultato.

**Comment by Cruyff97** [comment]
Parlando con @astagi crediamo sia un comportamento che avviene solo su Vercel, in locale il Menu funziona perfettamente. Sarebbe da testare su Github Pages.

**Comment by alenap93** [comment]
ciao @Cruyff97, io lo riscontro anche in locale, ho indagato un po, su questo vercel: https://design-angular-fynoyuwf0-dip-trasformazione-digitale.vercel.app/design-angular-kit#/info/welcome del commit https://github.com/italia/design-angular-kit/commit/eb05ebd56fdb843f7ed8cd1ee5d46d443eaa2898 (ne ho trovato uno a caso), il pulsante funziona correttamente, ad occhio penso che ora non funge perchè è stato rimosso (giustamente) lo script js di bootstrap (vedevo i data attributes che penso servano per i listener) dall'angular.json. Se così fosse penso vada implementata una logica nativa in angular, senza avere riferimenti al js di bootstrap.

**Comment by Cruyff97** [comment]
Riscontro anch'io ora il problema in locale, sono d'accordo sulla soluzione proposta.

**Comment by astagi** [comment]
@Cruyff97 @alenap93 allora si confermo che i data attribute servono per le attivazioni dei componenti, ho riscritto il branch `main` dove erano state riportate erroneamente vecchie modifiche, adesso è tornato con script js di bootstrap rimosso, faccio di nuovo prove Vercel/locale e vediamo da dove ripartire. Se credete sia più consona un'implementazione pure Angular ben venga!

**Comment by astagi** [comment]
@Cruyff97 @alenap93 sembra che nessun click funzioni più, neanche le tab che switchato su API. Probabilmente si, andava tramite i data-toggle. @Cruyff97 posso assegnare a te?

**Comment by Cruyff97** [comment]
@astagi Si ok, ci do' un'occhiata appena possibile.

**Comment by astagi** [comment]
Grazie mille @Cruyff97 !

**Comment by astagi** [comment]
@Cruyff97 @alenap93 ho inserito all'interno della doc il link alla cdn per bootstrap italia non bundle.. penso possa essere sufficiente visto la doc è stata costruita con il data binding di BSI, inoltre non dovrebbe in alcun modo interferire con i componenti. Direi di chiudere la issue.

**Comment by astagi** [comment]
Per ora chiudo, poi magari ne riapriamo una ad hoc per switchare ai componenti angular
