### ISSUE TITLE
Bug: binding class in IconComponent non funzionante

### ISSUE THREAD

**Issue by AntoninoBonanno** [italia/design-angular-kit#187]
## Comportamento atteso
Si aspetta di poter utilizzare questa sintassi:
```
<it-icon name="arrow-left"  [class.me-2]="isShowText"></it-icon>
```

## Comportamento attuale
Come verificato da @alenap93 in #171, il binding dell'attributo `class` nel componente `IconComponent` non è funzionante

**Comment by alenap93** [comment]
@AntoninoBonanno ad occhio potremmo cambiare l'input da class a classes

**Comment by astagi** [comment]
@AntoninoBonanno @alenap93 ci sono aggiornamenti qua?
