### ISSUE TITLE
Enhance iconHref in IconComponent

### ISSUE THREAD

**Issue by MartialDao** [italia/design-angular-kit#235]
## Descrizione
Si vorrebbe avere il path relativo di iconHref in modo che le icone possano essere visibili anche con un pubblicazione non sulla root del dominio senza dover creare regole apache o nginx nel risolvere la cartella di destinazione delle icone

## Comportamento attuale
Attualmente un progetto pubblicato nella root del dominio funziona perfettamente e risolve le icone di bootstrap-italia mente se viene pubblicato in una sottocartella del dominio va a rompere il caricamento delle icone

## Possibili soluzioni
modificando iconHref da `/bootstrap-italia/dist/svg/sprites.svg#it-${this.name}` a `./bootstrap-italia/dist/svg/sprites.svg#it-${this.name}` risolve il problema

**Comment by traycold** [comment]
È possibile rendere il path dove reperire le icone di bootstrap-italia (sprites.svg) parametrico e non scolpito?
Nel mio caso d'uso non è possibile modificare il path in cui sono disponibili le risorse di bootstrap-italia e quindi non si riescono a visualizzare le icone.
Ho visto che ad esempio per quanto riguarda i file statici delle traduzioni i18n è stato già fatto qualcosa del genere (si riesce a inserire il path custom tramite opportuna dichiarazione nel file app.module.ts " .. new TranslateHttpLoader(httpClient,'/path/custom/design-angular-kit/i18n/') .. " ).

Se si potesse fare qualcosa del genere anche per le icone, si risolverebbe questo problema.
