### ISSUE TITLE
BUG: Input label with browser autofill

### ISSUE THREAD

**Issue by AntoninoBonanno** [italia/design-angular-kit#236]
## Comportamento atteso

Quando avviene l'auto completamento da parte del browser la label degli input deve essere attiva

## Comportamento attuale

Attualmente la label degli input si sovrappone con il valore impostato dal browser (bug riscontrato su firefox)

![autofill](https://user-images.githubusercontent.com/56137431/229112343-9364ad86-37eb-4393-af74-cd05da3ba473.jpg)

**Comment by antenucci96** [comment]
In chrome il bug è ancora presente
