### ISSUE TITLE
BUG: Input label with browser autofill

### ISSUE THREAD

**Issue by antenucci96** [italia/design-angular-kit#238]
## Comportamento atteso
Quando avviene l'auto completamento da parte del browser la label degli input deve essere attiva #236

## Comportamento attuale
Il bug è riscontrato in chrome con lo stesso comportamento della issue #236
![Screenshot_20230403_095344](https://user-images.githubusercontent.com/60515229/229446332-a5d94105-3659-4a2d-ae3f-77ff7053dd0c.jpeg)

**Comment by AntoninoBonanno** [comment]
Ciao @antenucci96 non riesco a riprodurre il problema (mi sembra funzionare sia su chrome che su firefox)

Mi puoi dare maggiori informazioni?
- versione del [design-angular-kit](https://github.com/italia/design-angular-kit) usata
- versione di angular
- un esempio riproducibile

**Comment by antenucci96** [comment]
Preciso che il bug si presenta solo quando c'è il tag <it-input-password>.
In una schermata di autenticazione ad esempio, dopo aver salvato le credenziali in chrome

**Comment by AntoninoBonanno** [comment]
@antenucci96 sono riuscito a riprodurre il problema.
Sembra essere un bug di chrome vedi [issue nel repository di angular](https://github.com/angular/angular/issues/30616)

Facendo alcune prove, il browser non effettua il trigger dell'evento `change` nell'input finche non viene effettuato un click sulla pagina, infatti fino a quel momento il valore dell'input sembra essere null.

Ciò su firefox non avviene.

![Untitled-Project](https://user-images.githubusercontent.com/56137431/230778298-c60d7e3f-46e0-4055-b6c1-6589aeed3b3b.gif)


Una possibile soluzione sarebbe quella di inserire la regola scss
```scss
.form-group {
  input:-webkit-autofill ~ label:not(.active) {
    transform: translateY(-75%);
  }
}
```
e trasformare l'html da 
```html
<label.... >
<input.... >
```
a 

```html
<input.... >
<label.... >
```

@astagi questo problema si verifica anche sulla libreria [bootstrap-italia](https://github.com/italia/bootstrap-italia)?
in tal caso non sarebbe meglio applicare questo fix direttamente sulla libreria principale piuttosto che sul design-angular-kit?

**Comment by astagi** [comment]
@antenucci96 @AntoninoBonanno provo sulla libreria Bootstrap Italia, in alternativa possiamo già qua modificare il componente e aggiungere la regola css. Unico dubbio se invertire input e label può dare problemi di accessibilità.

**Comment by AntoninoBonanno** [comment]
@astagi ho trovato una soluzione senza dover spostare la posizione della label 

```css
.form-group {
  label:not(.active):has(+ input:-webkit-autofill) {
     transform: translateY(-75%);
  }
}
```

farò un PR in giornata
