### ISSUE TITLE
BUG: hardcoded iconHref in IconComponent

### ISSUE THREAD

**Issue by traycold** [italia/design-angular-kit#242]
## Comportamento atteso
Con il fix del bug #235, si è introdotto nel nostro scenario l'impossibilità di caricare le icone di bootstrap-italia. Infatti nel nostro scenario la webapp Angular è deployata in un path dinamico del dominio, in un contesto di Microfrontend. Non è possibile ipotizzare di deployare le risorse statiche necessarie (sprites.svg) in tutti gli N path possibili (N è nell'ordine di grandezza di 1.000).
Prima del fix del bug #235 il problema non si poneva perchè bastava rendere disponibili le risorse di bootstrap italia al path root del dominio.

## Comportamento attuale
Durante il caricamento della webapp il path di iconHref viene posto come relativo al contesto della webapp angular e non è pertanto possibile caricare le icone di bootstrap-italia.

## Possibili soluzioni
La soluzione ideale sarebbe rendere parametrico il path usato per comporre iconHref (utilizzando ad esempio la stessa tecnica con cui il path dei file di messaggi i18n può essere parametrizzato nel file app.module.ts).

**Comment by AntoninoBonanno** [comment]
Ciao, 
si potrebbe impostare il path in modo opzionale durante l'importazione del modulo ad esempio

```
@NgModule({
  imports: [
    ...
    DesignAngularKitModule.forRoot({iconHref: './bootstrap-italia/dist/svg/sprites.svg'})
  ]
})
```

Farò il fix per la prossima release
