### ISSUE TITLE
BUG: mancanza del placeholder e dell'icona calendario nell'input di tipo data da mobile

### ISSUE THREAD

**Issue by antenucci96** [italia/design-angular-kit#255]
## Comportamento atteso
L'input dovrebbe mostrare il placeholder mm/gg/yyyy e l'icona anche da mobile
![Screenshot_20230606_145607](https://github.com/italia/design-angular-kit/assets/60515229/b18e3437-bf2e-466f-ac1d-aea03f019924)

## Comportamento attuale
Il placeholder e l'icona non vengono mostrati
![Screenshot_20230606_145647](https://github.com/italia/design-angular-kit/assets/60515229/083233bd-5b9c-4f15-a52d-e3fd6a9046ee)

## Contesto
Il bug si presenta sia su Android utilizzando browser diversi che su IOS.
Design angular kit 1.0.0-16, Angular 15

**Comment by AntoninoBonanno** [comment]
Il problema si presenta anche nella libreria bootstrap-italia 
![msg755937492-3709](https://github.com/italia/design-angular-kit/assets/56137431/9b45f49a-2fde-4f70-9ce3-628948465975)

@astagi

**Comment by astagi** [comment]
Grazie della segnalazione @antenucci96 . Non saprei sembra dovuto alla renderizzazione del tipo date field che in questo caso è nativo. Il componente risulta comunque funzionante anche su mobile. Personalmente eviterei [eventuali hack](https://stackoverflow.com/questions/20321202/not-showing-placeholder-for-input-type-date-field) e se siete d'accordo chiuderei la issue.
