### ISSUE TITLE
[BUG] Errore 404 sito documentazione 

### ISSUE THREAD

**Issue by AntoninoBonanno** [italia/design-angular-kit#256]
Il sito [https://italia.github.io/design-angular-kit](https://italia.github.io/design-angular-kit) ha dei problemi di routing

## Comportamento attuale

Andando in un url specifico della documentazione (ad esempio [https://italia.github.io/design-angular-kit/design-angular-kit#/info/welcome](https://italia.github.io/design-angular-kit/design-angular-kit#/info/welcome)) viene mostrato un errore 404

Ciò causa anche un errore sul caricamento delle traduzioni.

L'unico modo per accedere alla documentazione è dall'URL [https://italia.github.io/design-angular-kit](https://italia.github.io/design-angular-kit) e successivamente, tramite menù, spostarsi nella pagina desiderata. Il refresh della pagina mostra l'errore 404.

## Comportamento atteso

Dovrebbe essere possibile raggiungere qualsiasi url della documentazione

**Comment by astagi** [comment]
Concordo @AntoninoBonanno questo è un bel bug :/ non so a cosa sia dovuto forse è un'impostazione del motore di documentazione!

**Comment by AntoninoBonanno** [comment]
Alla prossima release provo a rilasciare un file .htaccess con le regole di rewrite per Angular

**Comment by astagi** [comment]
Può essere un'idea!

**Comment by AntoninoBonanno** [comment]
@astagi Forse qui c'è una soluzione migliore [https://angular.io/guide/deployment#server-configuration](https://angular.io/guide/deployment#server-configuration) (guarda la sezione github pages)

**Comment by AntoninoBonanno** [comment]
Riapro perchè purtroppo non si è risolta con #260

**Comment by AntoninoBonanno** [comment]
@astagi eseguendo manualmente il workflow "Update documentation" il fix #260  sembra funzionare

**Comment by astagi** [comment]
@AntoninoBonanno su questo ci guardo stasera, mi sembra ancora presente il problema :/

**Comment by astagi** [comment]
Ah no aspetta in update_documentation ci sta questa stringa, ho riguardato ora

```yaml
      - run: cp dist/design-angular-kit-bundle/index.html dist/design-angular-kit-bundle/404.html
```

Provo a inserirla magari risolve il problema, probabile.

**Comment by astagi** [comment]
Lo metto fixato tramite questo commit https://github.com/italia/design-angular-kit/commit/2a13c42c39c2222f5302f97d71ff8734f49a8e55 , alla prossima release vedremo :)
