### ISSUE TITLE
Errore durante installazione del pacchetto

### ISSUE THREAD

**Issue by brigghius** [italia/design-angular-kit#263]
Ciao a tutti, ho creato un progetto che prevede bootstrap italia.

## Comportamento attuale
Ho eseguito il comando npm install design-angular-kit@unstable --save come da guida, ma si interrompe e va in errore
![image](https://github.com/italia/design-angular-kit/assets/49524691/c171d416-b5b0-4d22-9a78-690c011b2874)

## Contesto
questo di seguito è il package.json
![image](https://github.com/italia/design-angular-kit/assets/49524691/a9698bf6-7f01-4713-811f-210b104364f4)
come potete vedere sto usando angular 15.
è possibile qualche incongruenza con questa versione di angulare e l'attuale versione del design angular kit?

grazie in anticipo

**Comment by brigghius** [comment]
> Stai provando a installare l'ultima versione della libreria che richiede Angular 16 su Angular 15.
> 
> Dovresti [aggiornare il tuo progetto ad Angular 16](https://update.angular.io/?v=15.0-16.0)

Intanto grazie mille per la risposta.
Se invece io volessi mantenere per necessità di progetto Angular 15, quale versione del kit è compatibile?

**Comment by brigghius** [comment]
> Stai provando a installare l'ultima versione della libreria che richiede Angular 16 su Angular 15.
> 
> Dovresti [aggiornare il tuo progetto ad Angular 16](https://update.angular.io/?v=15.0-16.0)

allora, ho aggiornato alla versione 16 ed è ok adesso, però quando lo avvio ho un problema.
![image](https://github.com/italia/design-angular-kit/assets/49524691/67cedc34-ecb6-48c6-823c-5bc999e6a2dc)

seguendo questo passaggio l'applicativo non carivca e va in errore con il TranslateStore:
![image](https://github.com/italia/design-angular-kit/assets/49524691/261e1200-9423-4a9d-971c-9f2a90852dca)

nella guida dice di aggiungerlo ai providers, però non mi fa fare l'import automatico e non so come risolvere l'errore che mi da
![image](https://github.com/italia/design-angular-kit/assets/49524691/b10f9833-3af4-4a23-8ca0-384986104ea0)

come faccio a risolvere questo problema?

**Comment by AntoninoBonanno** [comment]
La versione 1.0.0-16 è l'ultima versione compatibile con Angular 15

Per l'errore del TranslateModule puoi importare manualmente con `import { TranslateStore } from '@ngx-translate/core';` 

`@ngx-translate/core`  è un `peerDependencies` quindi viene installato automaticamente. Se vuoi abilitare l'import automatico dovresti aggiungere `ngx-translate` al tuo package.json con `npm install @ngx-translate/core`

**Comment by brigghius** [comment]
> La versione 1.0.0-16 è l'ultima versione compatibile con Angular 15
> 
> Per l'errore del TranslateModule puoi importare manualmente con `import { TranslateStore } from '@ngx-translate/core';`
> 
> `@ngx-translate/core` è un `peerDependencies` quindi viene installato automaticamente. Se vuoi abilitare l'import automatico dovresti aggiungere `ngx-translate` al tuo package.json con `npm install @ngx-translate/core`

grazie mille!
mi riporta degli errori per una chiamata a i18n per il json della traduzione, però funziona 
![image](https://github.com/italia/design-angular-kit/assets/49524691/5633c024-f6c8-4155-9916-b32a501df288)
![image](https://github.com/italia/design-angular-kit/assets/49524691/2d0f47f3-3a6b-4a5c-8eed-8aa7ac49856c)

**Comment by AntoninoBonanno** [comment]
Come da istruzioni dovresti aggiungere al tuo `angular.json`

```
 "assets": [
    ...
    {
      "glob": "**/*",
      "input": "./node_modules/design-angular-kit/assets/i18n",
      "output": "/bootstrap-italia/i18n/"
    }
  ]
  ```

**Comment by brigghius** [comment]
grande! risolto
