### ISSUE TITLE
Componente it-select caricamento dinamico delle option

### ISSUE THREAD

**Issue by smeligrana** [italia/design-angular-kit#264]
Sto utilizzando il componente it-select all'interno di un form 

`<it-select label="Nazione" formControlName="nazione" > 
    <option value="" hidden="hidden">Seleziona un elemento</option>
    <option *ngFor="let n of nazioni" [value]="n.idNazione" >{{n.denominazione}}</option>
</it-select>`

quando tramite form.patchValue imposto il valore di nazione se il servizio che carica l'elenco delle nazioni non ha terminato di caricare non vedo la nazione selezionata.
Mentre se al posto del ngFor su option utilizzo [options] si it-select si comporta correttamente.

Si tratta di un bug?

**Comment by AntoninoBonanno** [comment]
Si, farò qualche verifica

**Comment by astagi** [comment]
@smeligrana potresti fornire un esempio completo della problematica? Grazie mille

**Comment by smeligrana** [comment]
Ecco l'eslempio 
HTML
```
<p class="example-section">
    <it-select
      id="default-select"
      label="Etichetta"
      [(ngModel)]="selectedValue"      
      defaultOption="Seleziona un elemento">
      
      <option *ngFor="let option of selectOptions" [value]="option.value">{{option.text}}</option>

    </it-select>
  </p>

  <button (click)="aggiorna()">Aggiorna</button>
```

TS
```
selectOptions: Array<SelectControlOption> = [
    {
      value: 1,
      text: 'Opzione 1'
    },
    {
      value: 2,
      text: 'Opzione 2'
    },
    {
      value: 3,
      text: 'Opzione 3'
    }
  ];

  aggiorna() {
    of().subscribe(() => {
      this.selectOptions = [
        {
          value: 4,
          text: 'Opzione 4'
        },
        {
          value: 5,
          text: 'Opzione 5'
        },
        {
          value: 6,
          text: 'Opzione 6'
        }
      ];
    });
  }
```

**Comment by astagi** [comment]
> Ecco l'eslempio HTML
> 
> ```
> <p class="example-section">
>     <it-select
>       id="default-select"
>       label="Etichetta"
>       [(ngModel)]="selectedValue"      
>       defaultOption="Seleziona un elemento">
>       
>       <option *ngFor="let option of selectOptions" [value]="option.value">{{option.text}}</option>
> 
>     </it-select>
>   </p>
> 
>   <button (click)="aggiorna()">Aggiorna</button>
> ```
> 
> TS
> 
> ```
> selectOptions: Array<SelectControlOption> = [
>     {
>       value: 1,
>       text: 'Opzione 1'
>     },
>     {
>       value: 2,
>       text: 'Opzione 2'
>     },
>     {
>       value: 3,
>       text: 'Opzione 3'
>     }
>   ];
> 
>   aggiorna() {
>     of().subscribe(() => {
>       this.selectOptions = [
>         {
>           value: 4,
>           text: 'Opzione 4'
>         },
>         {
>           value: 5,
>           text: 'Opzione 5'
>         },
>         {
>           value: 6,
>           text: 'Opzione 6'
>         }
>       ];
>     });
>   }
> ```

Gentilissimo grazie! Faremo le opportune verifiche prima della release stabile.

**Comment by AntoninoBonanno** [comment]
@smeligrana scusa per la tarda risposta.

Ho provato questo codice

```html
<p class="example-section">
    <it-select
      id="default-select"
      label="Etichetta"
      [(ngModel)]="selectedValue"
      defaultOption="Seleziona un elemento">

      <!--Puoi inserire gli option da html o dall'attributo options-->
      <option *ngFor="let option of selectOptions" [value]="option.value">{{option.text}}</option>

    </it-select>
  </p>
  <button (click)="aggiorna()">Aggiorna</button>
```

```typescript
selectOptions: Array<SelectControlOption> = [
    {
      value: 2,
      text: 'Opzione 2'
    },
    {
      value: 3,
      text: 'Opzione 3'
    }
  ];

  aggiorna() {
    of(undefined).subscribe(() => {
      this.selectOptions = [
        {
          value: 4,
          text: 'Opzione 4'
        },
        {
          value: 5,
          text: 'Opzione 5'
        },
        {
          value: 6,
          text: 'Opzione 6'
        }
      ];
    });
  }
```

E sembra funzionare.

ho provato anche a simulare una chiamata api

```typescript
export class SelectExampleComponent implements OnInit {
  selectedValue: number = null;
  selectOptions: Array<SelectControlOption> = [];

  ngOnInit() {
    timer(5000).subscribe(() => {
      this.selectOptions = [
        {
          value: 4,
          text: 'Opzione 4'
        },
        {
          value: 5,
          text: 'Opzione 5'
        },
        {
          value: 6,
          text: 'Opzione 6'
        }
      ];
    });
  }
  ```
E anche in questo caso sembra funzionare

**Comment by smeligrana** [comment]
Ho provato a riprodurre l'errore sull'ultima versione e si comporta correttamente, avevo notato l'errore su una precedente versione. Se non è stato corretto esplicitamente probabilmente è un side effect di qualche altra attività o aggiornamento di qualche altra libreria.

L'importante e che adesso funzioni.
