### ISSUE TITLE
Inserire il totale nella paginazione rompe l'allineamento

### ISSUE THREAD

**Issue by inaitana** [italia/design-angular-kit#274]
## Comportamento atteso
Sto utilizzando il paginator illustrato https://italia.github.io/design-angular-kit/design-angular-kit#/componenti/pagination, con alignment="center" come da primo esempio.
Aggiungendo il totale elementi come ng-content dell'elemento, mostrato nell'ultimo esempio, mi aspetterei che il paginator continui ad essere allineato al centro.

## Comportamento attuale
Se il paginator ha un contenuto all'interno, allora risulta allineato a sinistra, a causa degli stili legati alla classe .paginator-total che viene aggiunta.

## Possibili soluzioni
Introdurre un div dentro l'elemento nav.pagination-wrapper, con display: flex, e spostare l'aggiunta del justify-content (in questo caso center) su questo div.
Rimuovere lo stile display: flex da nav.pagination-wrapper e display: inline-flex da nav.pagination-wrapper.pagination-total.
Lasciare il tag p con l'ng-content fuori dal div introdotto.

**Comment by smeligrana** [comment]
Sembra che il problema sia presente anche utilizzando direttamente bootstrap italia

**Comment by astagi** [comment]
Grazie @inaitana ci attiviamo subito per la risoluzione su Bootstrap Italia.
