### ISSUE TITLE
[BUG] Posizione componenti it-select

### ISSUE THREAD

**Issue by antenucci96** [italia/design-angular-kit#285]
## Comportamento atteso
I componenti _it-select_ dovrebbero apparire allineati ai componenti _it-input_

## Comportamento attuale
Il border degli elementi appare più in basso rispetto ai componenti  _it-input_
![Screenshot_20231211_102503](https://github.com/italia/design-angular-kit/assets/60515229/8838efb0-9687-478f-9696-963e3dd2e616)

## Contesto
Il comportamento si verifica a partire dalla versione 2.7.9 di bootstrap-italia.
Di seguito il codice HTML
```html
<div class="row variable-gutters pt-1 pt-xl-1">
      <div class="col-lg-4">
        <div class="form-group">
          <it-input type="text" label="Nome"></it-input>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="form-group">
          <it-select label="Stato">
            <option value="1">Attivo</option>
            <option value="2">In scadenza</option>
            <option value="3">Scaduto</option>
          </it-select>
        </div>
      </div>
    </div>
```

**Comment by astagi** [comment]
@antenucci96 ho aperto una PR per un fix generale sui campi di input e i form, il problema posto qua sarà risolto su quel branch ma occorre fixare e rilasciare Bootstrap Italia, riscontro il problema anche lì.
