### ISSUE TITLE
[BUG] le label delle componenti native non si attivano

### ISSUE THREAD

**Issue by antenucci96** [italia/design-angular-kit#286]
## Comportamento attuale
Le label delle componenti _it-input_ si attivano, mentre utilizzando _input_ nativo no.
![Peek 2023-12-11 13-03](https://github.com/italia/design-angular-kit/assets/60515229/754d33dd-dc2f-4c80-ad3c-ce710845d262)
Nel campo Nome è utilizzato _it-input_, nel campo cognome _input_
Di seguito il codice
```html
<div class="row variable-gutters pt-1 pt-xl-1">
      <div class="col-lg-4">
        <div class="form-group">
          <it-input type="text" label="Nome"></it-input>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="form-group">
          <label for="input-prova">Cognome</label>
          <input id="input-prova" type="text">
        </div>
      </div>
    </div>
``` 

## Contesto
Il comportamento si verifica dalla versione di bootstrap-italia 2.7.9 in poi

**Comment by AntoninoBonanno** [comment]
Nel componente it input la classe "active" sulla label viene impostata tramite typescript.

Questa issue dovrebbe andare sulla libreria di bootstrap-italia non qui in quanto il componente Angular funziona correttamente.

**Comment by astagi** [comment]
Nel caso specifico del tuo esempio @antenucci96 non stai usando `form-control` come classe come nella documentazione di Bootstrap Italia nell'ultima versione. Come dice @AntoninoBonanno nel componente la label funziona correttamente.

**Comment by antenucci96** [comment]
Anche aggiungendo la classe  form-control il comportamento è lo stesso
