### ISSUE TITLE
Evento click su it-checkbox lancia due volte l'evento

### ISSUE THREAD

**Issue by smeligrana** [italia/design-angular-kit#293]
## Comportamento atteso
Se nel codice aggiungo 
`<it-checkbox [(ngModel)]="checked" label="Spuntato" (click)="click()"></it-checkbox>`

mi aspetto che il metodo click() venga richiamato una sola volta

## Comportamento attuale
Il metodo click() viene richiamato due volte

**Comment by astagi** [comment]
@smeligrana fixato qua, rilascio la versione entro domani https://github.com/italia/design-angular-kit/commit/6cf4b7fcb8459713b1bafffc38242584fc821e75
