### ISSUE TITLE
Ordinamento tabelle

### ISSUE THREAD

**Issue by mnuzzi** [italia/design-angular-kit#295]
## Comportamento atteso
L'utente clicca l'header di una tabella e il sistema richiama un metodo passando in input nome della colonna e direzione di ordinamento. Affianco all'header della colonna compare la freccia verso l'alto, la freccia verso il basso o nessuna freccia.

## Comportamento attuale
Attualmente le tabelle non gestiscono l'ordinamento.

## Possibili soluzioni
Angular Material offre già questa funzionalità e il codice segue licenza MIT.

**Comment by astagi** [comment]
Grazie @mnuzzi!
