### ISSUE TITLE
Separare la funzionalità di autocomplete in un nuovo componente

### ISSUE THREAD

**Issue by AntoninoBonanno** [italia/design-angular-kit#302]
## Comportamento atteso

Sarebbe opportuno separare la logica dell'auto-completamento in un componente separato, ciò permette di mantenere meglio la funzionalità e non appesantire il componente `it-input`

## Comportamento attuale

Attualmente il componente `it-input` include la funzionalità di [autocomplete ](https://italia.github.io/bootstrap-italia/docs/form/autocompletamento/)

## Possibili soluzioni

Realizzare il componente `it-autocomplete` che si dedica solo a questa funzionalità.

**Comment by astagi** [comment]
Concordo @AntoninoBonanno ! Posso prendermi in carico io questo task.

**Comment by Alfonso1998** [comment]
Buonasera, sto sviluppando un progetto in angular e sto usando design-angular-kit per i componenti. Vi volevo chiedere per quanto riguarda l'autocomplete, se c'era qualche implementazione in input o output che potesse migliorare questo comportamento , ho tanti dati da mostrare e il risultato è questo : 
![Acquisizione schermata 21 10 2024 alle 16 20 49  1](https://github.com/user-attachments/assets/3f050738-bcb2-4fdd-a7ed-b1714eefe3e8)
Grazie in anticipo , aspetto una vostra risposta, buona giornata
