### ISSUE TITLE
publiccode.yml non esistente

### ISSUE THREAD

**Issue by AntoninoBonanno** [italia/design-angular-kit#304]
https://github.com/italia/design-angular-kit/blob/87f1f900d8be8d17b7e2597ce3ea8f7cb221e18a/.github/workflows/pc-update.yml#L17C21-L17C35

Il Workflow pc-update.yml (Publiccode.yml update) fallisce. 

Error: Error: ENOENT: no such file or directory, open 'publiccode.yml'

**Comment by astagi** [comment]
Fixed by https://github.com/italia/design-angular-kit/commit/d60ce9500a9ef1199d0c48e75b4721e8b6b4e7ab
