### ISSUE TITLE
Create component Transfer

### ISSUE THREAD

**Issue by astagi** [italia/design-angular-kit#310]
## Description

Create component `Transfer` following the vanilla JS implementation present in [Bootstrap Italia documentation](https://italia.github.io/bootstrap-italia/docs/form/transfer/).

## Checklist

- [x] Verify and update, markup and classes of the resulting DOM template, compared to Bootstrap Italia 2
- [x] Check the rendering of the component (CSS application including spacing, dimensions, typography, ...), compared to Bootstrap Italia and the new UI kit
- [x] Check the behavior of the component (JavaScript, user interaction, states, keyboard interaction for accessibility, ...), compared to Bootstrap Italia 2
- [ ] Verify the accessibility of the component, including automatic tests and manual evaluations by a11y experts, if possible
- [ ] Evaluate the need to supplement documentation with more detailed information.
- [ ] Write tests for this component
- [x] Write documentation for this component

**Comment by Fupete** [comment]
@astagi ho aggiunto questa issue alla board census come "DA FARE". 
⚠️ Sarà da aggiornare lo status delle verifiche nella [board census ](https://github.com/orgs/italia/projects/32/views/1)alla risoluzione.

**Comment by Fupete** [comment]
Da considerare @astagi @valeriocomo che ci sono 4 segnalazioni di accessibilità aperte (https://github.com/italia/bootstrap-italia/issues?q=is%3Aissue+is%3Aopen+transfer) sul componente Bootstrap Italia al momento. Sarebbe opportuno aspettare la soluzione di queste e poi implementare anche qui quanto dovuto prima del merge.
