### ISSUE TITLE
Aggiungere un commento nella sezione input di tipo date 

### ISSUE THREAD

**Issue by SalvoDiblasi** [italia/design-angular-kit#313]
## Comportamento atteso
Mi aspetto che nel'input di tipo data ci sia un commento relativo al tipo di formato di data che vuole o la possibilità di far accettare quanto meno un formato italiano ( se è possibile )

## Comportamento attuale
Attualmente se nel form di Angular do al mio formControlName un valore di default in un formato diverso, come GG/MM/AAAA non vedo il valore lato front

Nello specifico se assegno nel mio ts un "this.myFormDate.setValue('30/01/2024') nell'html vedrò l'input senza il mio valore, quindi con il suo valore standard di default, ovvero: gg/mm/aaaa mentre se metto il formato "2024-01-01" mi fa vedere il valore lato front convertendolo poi nel formato italiano (GG/MM/AAAA)

## Possibili soluzioni
O inserire un commento o qualcosa che dica che tutti i valori che passano al tipo date devono essere di questo formato: YYYY-MM-DD o aggiungere la possibilità di far inserire in ingresso almeno il formato italiano (GG/MM/AAAA)

**Comment by AntoninoBonanno** [comment]
@astagi si può pensare di effettuare un parse della data in input al componente in modo da accettare tutte le date in formato stringa

**Comment by astagi** [comment]
@SalvoDiblasi @AntoninoBonanno visti i tempi stretti rimaniamo sul commento al valore di formato `YYYY-MM-DD` come riportato anche su MDN. Direi di aggiungere eventualmente una utility di formattazione date su Bootstrap Italia o utilizzare una libreria esterna.
