### ISSUE TITLE
Errore accessibilità componente It-Icon

### ISSUE THREAD

**Issue by carmelotaverniti** [italia/design-angular-kit#315]
## Comportamento atteso

Il componente it-icon dovrebbe consentire la specifica degli elementi aria.

`<it-icon name="tool">
<svg **aria-hidden="true"** class="icon"><use href="./bootstrap-italia/dist/svg/sprites.svg#it-tool" xlink:href="./bootstrap-italia/dist/svg/sprites.svg#it-tool"></use></svg>
</it-icon>`

oppure 

`<it-icon name="tool">
<svg **aria-label="My graphic"** class="icon"><use href="./bootstrap-italia/dist/svg/sprites.svg#it-tool" xlink:href="./bootstrap-italia/dist/svg/sprites.svg#it-tool"></use></svg>
</it-icon>`

etc.

## Comportamento attuale

Il componente it-icon non consente la specifica degli elementi aria
`<svg [class]="iconClass">
  <use [attr.href]="iconHref" [attr.xlink:href]="iconHref"></use>
</svg>
`
e produce il seguente html:

`<it-icon name="tool">
<svg class="icon"><use href="./bootstrap-italia/dist/svg/sprites.svg#it-tool" xlink:href="./bootstrap-italia/dist/svg/sprites.svg#it-tool"></use></svg>
</it-icon>`

**Comment by astagi** [comment]
Grazie @carmelotaverniti se ti senti confidente e puoi, apri pure una PR con questa modifica nel componente ItIcon
