### ISSUE TITLE
Label autocomplete non visualizzata

### ISSUE THREAD

**Issue by carmelotaverniti** [italia/design-angular-kit#316]
## Comportamento atteso

durante la compilazione del campo autocomplete dovrebbe visualizzarsi la label specificata "Cerca nel sito"
![image](https://github.com/italia/design-angular-kit/assets/117445050/c699f39a-a59b-4d00-8c1e-abb9fc981791)

## Comportamento attuale

la label "Cerca nel sito" specificata non viene visualizzata
![image](https://github.com/italia/design-angular-kit/assets/117445050/c9fd3d75-261d-43a4-ace0-759bbc7b9f53)

**Comment by AntoninoBonanno** [comment]
Nella documentazione di bootstrap-italia la label non appare 

[https://italia.github.io/bootstrap-italia/docs/form/input/#ricerca-con-autocompletamento](https://italia.github.io/bootstrap-italia/docs/form/input/#ricerca-con-autocompletamento)

Ho comunque aggiunto al componente autocomplete l'attributo `forceShowLabel` (default a `true`) per mostrare la label nell'autocomplete
