### ISSUE TITLE
Table con ItSort visualizza le frecce di ordinamento anche quando non è attivo l'ordinamento

### ISSUE THREAD

**Issue by smeligrana** [italia/design-angular-kit#323]
## Comportamento atteso
Quando non è ancora stato attivato l'ordinamento la freccia vicino all'etichetta della colonna  non dovrebbe essere visualizzata

## Comportamento attuale
Le frecce di ordinamento vengono sempre visualizzate
![image](https://github.com/italia/design-angular-kit/assets/10783657/8dd6c8a7-00ab-4232-af4d-9b03d50eb23e)

**Comment by astagi** [comment]
Grazie @smeligrana controllo la PR e la includo nella prossima versione!
