### ISSUE TITLE
ERROR NullInjectorError: R3InjectorError(_[NOME_MODULO]Module)[InjectionToken it-asset-base-path -> InjectionToken it-asset-base-path -> InjectionToken it-asset-base-path]: 

### ISSUE THREAD

**Issue by alldone** [italia/design-angular-kit#332]
## Comportamento atteso
durante l'iterazione di una lista (*ngFor) di tanto in tanto, quindi in modo non sistematico, viene mostrato l'errore seguente:
--When iterating through a list (*ngFor) the following error is occasionally shown:

ERROR NullInjectorError: R3InjectorError(_[NOME_MODULO]Module)[InjectionToken it-asset-base-path -> InjectionToken it-asset-base-path -> InjectionToken it-asset-base-path]: 
  NullInjectorError: No provider for InjectionToken it-asset-base-path!
    at NullInjector.get (core.mjs:4674:27)
    at R3Injector.get (core.mjs:5117:33)
    at R3Injector.get (core.mjs:5117:33)
    at R3Injector.get (core.mjs:5117:33)
    at ChainedInjector.get (core.mjs:16449:36)
    at lookupTokenUsingModuleInjector (core.mjs:6711:39)
    at getOrCreateInjectable (core.mjs:6759:12)
    at ɵɵdirectiveInject (core.mjs:10319:19)
    at ɵɵinject (core.mjs:3837:42)
    at inject (core.mjs:3921:12)

## Comportamento attuale
al presentarsi dell'errore, viene interrotto il rendering della view
-- when the error occurs, the rendering of the view is interrupted --

## Possibili soluzioni

Nel modulo che utilizza la libreria (    DesignAngularKitModule.forChild()  ) , ho inserito 
{
      provide: IT_ASSET_BASE_PATH,
      useValue: '../{path-a}/bootstrap-italia',
    }

quantomeno non rompe il rendering della view.... 

## Contesto

versione : "design-angular-kit": "^1.0.0-prerelease.3",

**Comment by astagi** [comment]
Buongiorno @alldone grazie per il report, come mai avviene in modo non sistematico? aggiungendo la path che cosa dovrebbe risolvere?

**Comment by alldone** [comment]
Buondì, poi ho capito dopo averlo temporaneamente fissato, avrei dovuto scriverlo pardon, praticamente spacca quando utilizzo componenti che introducono una risorsa grafica, tipo l'alert, quindi ho messo la dist di bootstrap-italia nell'asset ( oltre che come riferimento in angular.json) e ho aggiunto il provider nel modulo che usa la libreria facendo puntare alla cartellina nell'assets, ora SN a casa, appena arrivo a lavoro aggiungo il pezzettino di codice, ora nn so se era prevista dall'installazione e o un piccolo bug... Indirizzatemi voi. Grazie nel frattempo

**Comment by astagi** [comment]
Grazie @alldone lascio aperta la segnalazione e assegno ad @AntoninoBonanno (adesso è in ferie e rientrerà nella prossima settimana). Se hai eventuali informazioni una volta aggiunto il codice scrivi pure qua.

**Comment by astagi** [comment]
@alldone hai un progetto da condividere dove è possibile replicare il problema?

**Comment by AntoninoBonanno** [comment]
@alldone come vedi nel README è necessario utilizzare `provideDesignAngularKit` o `DesignAngularKitModule`

per capire qual'è il problema dovresti mandarci del codice per replicare il problema. Inoltre sarebbe utile indicare che tipo di configurazione stai usando (Applicazione standalone, Applicazione modulare, Applicazione ibrida)
