### ISSUE TITLE
Componente Timeline

### ISSUE THREAD

**Issue by stefanozanelliunitn** [italia/design-angular-kit#345]
Richiesta implementazione nuovo componente Timeline basato su linee guida BootstrapItalia.

Avrei in locale delle modifiche per implementare questo componente, ma vorrei un feedback da parte vostra.
Posso procedere con la pull-request e poi valutate voi se integrare o meno?

**Comment by astagi** [comment]
Ciao @stefanozanelliunitn molto interessante! direi che va bene aggiungere questo componente, potresti aprire un altro branch/PR rispetto a quello dello slimTitle? Grazie mille!

**Comment by astagi** [comment]
Mergiata
