### ISSUE TITLE
Animazione di chiusura assente su accordion/collapse con ng build

### ISSUE THREAD

**Issue by g-contaldi** [italia/design-angular-kit#349]
## Comportamento atteso

Sui componenti it-accordion e it-collapse, ma anche su qualsiasi elemento custom expand/collapse, mi sarei aspettato l'animazione anche alla chiusura, come avviene all'apertura.

## Comportamento attuale

Nessuna animazione presente alla chiusura di accordion/collapse, se fatto ng build sull'applicazione.

## Possibili soluzioni
// from bootstrap scss
.collapsing {
  height: 0;
  overflow: hidden;
  @include transition($transition-collapse);
}

La classe .collapsing viene correttamente aggiunta in chiusura. Penso che il problema risieda nel fatto che l'elemento non avendo un height settato, non ha un punto di partenza per arrivare a 0, e quindi non applica la transition.

L'animazione in chiusura torna a funzionare se imposto un height all'elemento con la classe collapse, ma non può essere la soluzione.

## Contesto

Il bug non si presenta se uso l'applicazione che consuma la libreria in locale (ng serve in localhost), dove quindi l'animazione funziona sia in apertura che in chiusura. Si presenta invece se faccio la build (build in locale consumata con http-server, ma anche sui vari ambienti sviluppo/collaudo ecc). Insomma se l'applicazione è buildata, non funziona l'animazione di chiusura su qualsiasi elemento expand/collapse. Il bug si presenta anche sulla vostra documentazione, ma non su quella di bootstrap italia o bootstrap.

**Comment by astagi** [comment]
Grazie @g-contaldi verifichiamo quanto prima

**Comment by alenap93** [comment]
@astagi penso che il problema sia dovuto al flag **optimization** nell'angular.json. Se questo è a true ottimizza sia script che stili che font e, ottimizzando gli script di bootstrap-italia, rompe qualcosa.
Al volo possiamo mettere per prod:
```
    "optimization": {
      "fonts": true,
      "scripts": false,
      "styles": true
    },
```
disabilitando l'ottimizzazione degli script, ma penso sia meglio portare dentro le animazioni gestendole con angular animations.

**Comment by astagi** [comment]
Grazie @alenap93 , chiamo in causa anche @AntoninoBonanno per la questione

**Comment by AntoninoBonanno** [comment]
Sinceramente non ho mai disabilitato l'ottimizzazione degli script. Se disabilitando questa opzione si disabilita anche l'ottimizzazione del codice Angular, sarebbe meglio gestire l'animazione direttamente in Angular

**Comment by g-contaldi** [comment]
Nel frattempo ho continuato a studiare la problematica, ed è un problema noto di integrazione di Bootstrap con Angular, di cui non è mai stata data una vera soluzione. Qui alcuni [workaround suggeriti](https://github.com/angular/angular-cli/issues/11439#issuecomment-433141561). L'unica vera soluzione che sembra non essere affetta dal problema, ma che non ho mai avuto il tempo di provarla, potrebbe essere quella di usare la direttiva [(ngCollapse)] dal package ngBootstrap al posto del "data-bs-toggle" nativo. Non so se avete voi modo e tempo di effettuare alcuni test, sempre che sia una strada percorribile quella di rimpiazzare attributi nativi di bootstrap con ngBootstrap.

**Comment by astagi** [comment]
> Nel frattempo ho continuato a studiare la problematica, ed è un problema noto di integrazione di Bootstrap con Angular, di cui non è mai stata data una vera soluzione. Qui alcuni [workaround suggeriti](https://github.com/angular/angular-cli/issues/11439#issuecomment-433141561). L'unica vera soluzione che sembra non essere affetta dal problema, ma che non ho mai avuto il tempo di provarla, potrebbe essere quella di usare la direttiva [(ngCollapse)] dal package ngBootstrap al posto del "data-bs-toggle" nativo. Non so se avete voi modo e tempo di effettuare alcuni test, sempre che sia una strada percorribile quella di rimpiazzare attributi nativi di bootstrap con ngBootstrap.

ciao @g-contaldi per la prossima release vediamo di testare questa soluzione, scusa il ritardo ma siamo stati impegnati in una pesante review di accessibilità.. grazie infinite! cc @AntoninoBonanno

**Comment by AntoninoBonanno** [comment]
Sconsiglierei di integrare ngBootstrap nella libreria poichè appesantirebbe la libreria di funzionalità non necessarie o duplicate.

Si potrebbe pensare di implementare [(ngCollapse)] in bootrstrap-italia

**Comment by valeriocomo** [comment]
Ciao a tutti. Ho provato a replicare il bug senza successo.
Ho usato la versione 1.1.2 della libreria e, come fatto da voi, ho buildato per production e servito da un server di file statici (http-server). 
Vi allego lo zip con un progetto d'esempio.
Il consiglio che mi sento di darvi è questo: confrontate il contenuto del file angular.json.
Probabilmente va aggiunta una reference nella configurazione di build del progetto.

Attendo feedback

[design-italia-angular-starterkit.zip](https://github.com/user-attachments/files/17648968/design-italia-angular-starterkit.zip)

**Comment by valeriocomo** [comment]
ciao @g-contaldi. Ho provato a riprodurre il bug con questo setup:

- angular v17
- design-angular-kit v1.0.3
- node 20

Ho lanciato l'applicazione sia in fase di sviluppo che come build di production, servita da un server di file statici.
Non sono riuscito a riprodurre il problema in nessuno dei casi. Ti allego il progetto.

[test-animations-v17.zip](https://github.com/user-attachments/files/17649665/test-animations-v17.zip)

**Comment by g-contaldi** [comment]
Ciao @valeriocomo, ho lanciato il progettino fatto da te ed effettivamente il bug non si presenta.

Ti allego qui un test che ho fatto io, dove invece il bug è presente, con:
- angular v16
- design-angular-kit v1.0.0-23 (ho preso l'ultima compatibile con a16)
- node 18

[test-collapse.zip](https://github.com/user-attachments/files/17945819/test-collapse.zip)

Immagino quindi che con qualche aggiornamento di versione di angular e/o bootstrap-italia, il problema sia stato fixato a monte.
Da una parte meglio, dall'altra peccato perché su questo progetto dove mi si verifica il bug non posso, almeno per il momento, salire di versioni.

Grazie per il supporto.

**Comment by valeriocomo** [comment]
ciao @g-contaldi. farò un test col progetto da te allegato.
