### ISSUE TITLE
Popover non viene caricato all'interno del container impostato

### ISSUE THREAD

**Issue by tbiondo** [italia/design-angular-kit#352]
Andrebbe aggiornato il namespace dell'attributo (bs) che viene assegnato all'elemento

https://github.com/italia/design-angular-kit/blob/a5979c77a78c52a66fded9c36815719a895f334b/projects/design-angular-kit/src/lib/components/core/popover/popover.directive.ts#L43

**Comment by AntoninoBonanno** [comment]
@tbiondo potresti descrivere meglio il problema, aggiungendo anche con un frammento di codice?

**Comment by tbiondo** [comment]
@AntoninoBonanno la funzione indicata inserisce l'attributo "data-container" in modo da poter impostare appunto il container al quale agganciare il popover, ma nelle ultime versioni di bootstrap l'attributo va impostato con il namespace "bs", infatti adesso non funziona. 
Di conseguenza,
this.element.setAttribute('data-container', container); -> this.element.setAttribute('data-bs-container', container);
Ti apro una pull request se preferisci.

**Comment by AntoninoBonanno** [comment]
La [documentazione ufficiale](https://italia.github.io/bootstrap-italia/docs/componenti/popover/#attivazione-con-opzione-container) indica `data-container` ma su bootstrap è `data-bs-container`.

@astagi puoi controllare?

@tbiondo, @astagi ho aperto la PR #368. Potete effettuare dei test prima di unirla alla main? grazie

**Comment by astagi** [comment]
Mergiata
