### ISSUE TITLE
Dropdown con icona custom al posto di label + freccetta

### ISSUE THREAD

**Issue by smartm0use** [italia/design-angular-kit#410]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

1.0.3

### Cosa

Ho bisogno di una dropdown che si apra cliccando su un'icona, "hamburger icon" nel mio caso.

### Perché

Non ho bisogno quindi di freccette su cui cliccare. C'è modo di farlo?

### Contesto

Questo è il mio codice:

```
<it-dropdown mode="button">
    <it-icon button name="more-items" class="bg-light" size="sm" color="primary" title="Apri menu azioni"></it-icon>
    <ng-container list>
        @for(item of items; track item.label) {
            <it-dropdown-item externalLink="false" active="true" (click)="openThis(item.label)">
                {{ item.label }}
            </it-dropdown-item>
        }
    </ng-container>
</it-dropdown>
```

**Comment by astagi** [comment]
Ciao @smartm0use premetto che non trattiamo nelle issue di customizzazioni (avere una dropdown senza freccia o con un'icona diversa andrebbe fuori dagli schemi del design system). In ogni caso la dropdown ha dei metodi pubblici quali `toggle` e `show`. Penso che creando una ref all'elemento puoi richiamare questi metodi all'evento del click dell'icona e aprire la dropdown.

**Comment by smartm0use** [comment]
Ho risolto riwrappando la dropdown di Bootstrap Italia. Grazie!

**Comment by smartm0use** [comment]
> Ciao @smartm0use premetto che non trattiamo nelle issue di customizzazioni (avere una dropdown senza freccia o con un'icona diversa andrebbe fuori dagli schemi del design system)

Per curiosità, con DAK come si può realizzare un dropdown di questo tipo? Non è un tipo di interazione abbastanza diffuso e consolidato per le interfacce grafiche?

![image](https://github.com/user-attachments/assets/0fd7646c-92c2-4d2b-806f-41cf3ac109f4)


> In ogni caso la dropdown ha dei metodi pubblici quali `toggle` e `show`. Penso che creando una ref all'elemento puoi richiamare questi metodi all'evento del click dell'icona e aprire la dropdown.

Ciò comunque non toglierebbe la freccetta, giusto? A meno di forzature tramite Javascript.

**Comment by astagi** [comment]
@smartm0use purtroppo utilizzando la dropdown non vai a togliere la freccia, è un componente che lavora in quel modo. Potresti provare in alternativa a dare una classe aggiuntiva alla dropdown per forzare con il CSS la freccia (dargli un `display: none`) e al posto della label mettere un `it-icon` . Manterresti la funzionalità con lo stile che ti serve.
