### ISSUE TITLE
Errore Could not resolve "projects/design-angular-kit/src/public_api" in fase di compilazione progetto

### ISSUE THREAD

**Issue by NicoloCasagrande** [italia/design-angular-kit#417]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

1.1.3

### Cosa

Durante il building dell'applicazione, una volta pushata su git, ricevo questo errore: 

✘ [ERROR] Could not resolve "projects/design-angular-kit/src/public_api"
    node_modules/design-angular-kit/fesm2022/design-angular-kit.mjs:16:22:
      16 │ import * as i1$5 from 'projects/design-angular-kit/src/public_api';
         ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  You can mark the path "projects/design-angular-kit/src/public_api" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
✘ [ERROR] TS2307: Cannot find module 'projects/design-angular-kit/src/public_api' or its corresponding type declarations. [plugin angular-compiler]
    node_modules/design-angular-kit/lib/components/navigation/skiplink/skiplink-item/skiplink-item.component.d.ts:1:36:
      1 │ ...plinkComponent } from 'projects/design-angular-kit/src/public_api';

Non vorrei aver impostato io qualcosa di sbagliato ma fino a due giorni fa non ho avuto problemi e non ho fatto aggiornamenti particolari al progetto.

### Perché

Non vorrei fosse un bug presente in alcune versioni o comunque qualcuno potrebbe essersi trovato nella stessa situazione.

**Comment by astagi** [comment]
Ciao @NicoloCasagrande grazie della segnalazione. Evidentemente c'è stato un errore di import all'interno della libreria, abbiamo rilasciato la versione `1.1.4` con i fix necessari, puoi dirmi se adesso ti funziona tutto?
