### ISSUE TITLE
Form input

### ISSUE THREAD

**Issue by Pasquale02** [italia/design-angular-kit#66]
## Comportamento atteso

Realizzare una componente di input form con lo stile di Design UI Kit.

[Form input Bootstrap Italia](https://italia.github.io/bootstrap-italia/docs/componenti/form-input/)

## Possibili soluzioni

Creare delle componenti Angular che rispecchino l'esempio di utilizzo seguente:

```html
<it-input 
	[type]="type" 
	[label]="label"
	[note]="note" 
	[placeholder]="placeholder"
	[pwStrengthMeter]="strengthPwd"
	[icon]="icon"
	[disabled]="disabled"
	[readOnly]="readOnly"
	[autoCompleteData]="autoCompleteData"
	[(ngModel)]="model">
</it-input> 
```
La componente `<it-input>` indica un campo di input ed accetta i seguenti parametri:
 - `type`: indica il tipo di campo. Puo' assumere i valori `text`, `email`, `password`, `number`, `tel`;
 - `label`: indica il valore della label da visualizzare;
 - `note`: indica il testo di aiuto sotto la input;
 - `placeholder`: indica il testo presente nel campo vuoto;
 - `pwStrengthMeter` (opzionale, default `false`) disponibile solo se il type e' `password`. Se presente indica se il widget di robustezza password e' presente. Accetta una espressione booleana o può essere usato come attributo senza valore;
 - `icon`: indica l'icona da visualizzare a sinistra del campo di input;
 - `disabled`: (opzionale, default `false`) indica se il campo in questione è disabilitato. Accetta una espressione booleana o può essere usato come attributo senza valore; 
 - `readOnly`: (opzionale, default `false`) indica se il campo in questione è di sola lettura. Accetta una espressione booleana o può essere usato come attributo senza valore;
 - `autoCompleteData`: indica la lista di elementi ricercabili su cui basare il sistema di autocompletamento della input;
 - `ngModel`: indica la compatibilita' con il binding bidirezionale sul valore della input.

**Comment by ciccio86** [comment]
La issue è stata suddivisa nell issue #76, #77, #81 e #83

**Comment by astagi** [comment]
@ciccio86 @Pasquale02 @snack-eater è con grande piacere che vi annuncio che i lavori su Angular Kit sono ufficialmente ripartiti grazie al lavoro di @cri99 che seguirà i prossimi sviluppi 🙌 Vista l'anzianità di queste issue, vado a chiuderle :) 

Issue di riferimento: https://github.com/italia/design-angular-kit/issues/126
Discussione: https://github.com/italia/design-angular-kit/discussions/127
