### ISSUE TITLE
Readme NPM registry

### ISSUE THREAD

**Issue by nsanitate** [italia/design-angular-kit#74]
## Comportamento atteso

La pagina NPM registry dedicata al progetto dovrebbe avere un Readme.

## Comportamento attuale

Attualmente la pagina si presenta vuota.

**Comment by francescozaia** [comment]
Curioso, dovrebbe usare automaticamente il README.md di GitHub... 🤔

**Comment by nsanitate** [comment]
Penso sia necessario aggiungerlo al pacchetto npm o giocare con le configurazioni di npmjs.com
