### ISSUE TITLE
Test di Accessibilità

### ISSUE THREAD

**Issue by giuseppe-santoro** [italia/design-angular-kit#8]

**Comment by ciccio86** [comment]
A questo [link](https://www.guru99.com/accessibility-testing.html) ci sono delle informazioni che riguardano l'accessibility testing.

**Comment by ciccio86** [comment]
Seguendo le linee guida a questo [link](https://angular-2-training-book.rangle.io/handout/a11y/), ciò che dovrebbe essere testato in ambito accessibilità è:

- Markup semantico
    - elementi semantici (`<nav>`, `<header>`, `<main>`,... al posto dei semplici `<div>`)
    - attributi `alt` alle immagini
    - meta attributi ARIA ([https://www.w3.org/TR/wai-aria/](https://www.w3.org/TR/wai-aria/))
- Accessibilità via tastiera
    - gestione del focus sugli elementi della pagina
    - gestione corretta dei `tabindex` per definire la corretta sequenza di focus degli elementi della pagina
    - transizioni di focus ad esempio all'apertura di Dialog modali
    - comportamenti Angular assegnati agli elementi a cui di default il browser permette di essere focusable (`<button>`, `<input>`, `<a>`)

In generale una applicazione dovrebbe essere:

### Leggibile

Rispondere alle seguenti domande:

- La pagina può essere ridimensionata al 200% ed essere usabile?
- Le dimensioni del testo sono appropriate sui diversi dispositivi?
- Il contrasto dei colori è sufficiente?

### Predicibile

Rispondere alle seguenti domande:

- L'autoplay di video e musica è spento?
- L'utente è avvisato di qualsiasi cambio di contesto (cambio pagina, ...)?
- Gli screen reader hanno abbastanza tempo per leggere gli elementi che compaiono dinamicamente nella pagina (alerts, contenuto renderizzato via javascript)?

### Navigabile

Rispondere alle seguenti domande:

- Tutti i task di base possono essere completati utilizzando esclusivamente la tastiera?
- I form possono essere completati esclusivamente usando la tastiera?
- E' presente una indicazione visuale che indichi l'elemento con il focus in un determinato momento?
- Durante i cambi di contesto il focus viene spostato in maniera appropriata?

Inoltre si dovrebbe testare le componenti utilizzando uno screen reader oltre che i classici browser.

**Comment by ciccio86** [comment]
Aggiungere la descrizione di cosa dovrebbe essere testato nel file README.

**Comment by ciccio86** [comment]
Nel README è già presente un link alle linee guida per il design. In generale, per ogni componente, dovrebbero essere specificati esplicitamente nell'issue tracker i requisiti di accessibilità.
