### ISSUE TITLE
Sostituzione tab documentazione

### ISSUE THREAD

**Issue by ciccio86** [italia/design-angular-kit#86]
## Comportamento atteso

I tab `Descrizione`, `API` ed `Esempi` presenti nella pagina di documentazione di ogni componente dovrebbero utilizzare l'apposita componente `Tab` della libreria.

## Comportamento attuale

Al momento sono utilizzati i tab nativi di Bootstrap Italia.

**Comment by francescozaia** [comment]
Mi sembra di ricordare che questo permetterebbe di rimuovere l'inclusione di jQuery?

**Comment by ciccio86** [comment]
@francescozaia esatto. bisognerebbe controllare se ci sono altre dipendenze, anche se da un primo giro che ho fatto non mi sembra.
