### ISSUE TITLE
Aggiornare la dipendenza Bootstrap Italia

### ISSUE THREAD

**Issue by francescozaia** [italia/design-angular-kit#95]
## Comportamento atteso
Vorremmo aggiornare la dipendenza Bootstrap Italia alla versione stabile.

**Comment by astagi** [comment]
@francescozaia è con grande piacere che ti annuncio che i lavori su Angular Kit sono ufficialmente ripartiti grazie al lavoro di @cri99 che seguirà i prossimi sviluppi 🙌
